[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
staking_protocol = "6LPbRMtHA5KtgmrYCwQMRuDNLnEUgKxUcTHKLXRF9s3e"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
