[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
staking_protocol = "5VL2tMf1K4hf1GVKzo1Z3AjXAeF4XGMurm8AdjDC2FEv"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
